name = "vibes-diy-dev"
main = "cf-worker/vibe-meta.ts"
compatibility_date = "2025-02-24"
compatibility_flags = ["nodejs_compat"]

vars = { ENVIRONMENT = "test" }

#[observability.logs]
#enabled = true

[assets]
directory = "build/client"
binding = "ASSETS"
html_handling = "force-trailing-slash"
#not_found_handling = "single-page-application"
#run_worker_first = true

[env.production]
vars = { ENVIRONMENT = "production" }
name = "vibes-diy-prod"

[env.dev]
vars = { ENVIRONMENT = "dev" }
name = "vibes-diy-dev"

