name: Deploy Hosting Worker
description: Deploy the vibes.diy hosting worker to Cloudflare

inputs:
  environment:
    description: "Environment to deploy to (dev, production, preview)"
    required: true
    default: "production"
  worker_name:
    description: "Name of the worker to deploy to"
    required: false
    default: ""
  CLOUDFLARE_API_TOKEN:
    description: "Cloudflare API token for deployment"
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: "Cloudflare account ID"
    required: true
  SERVER_OPENROUTER_API_KEY:
    description: "OpenRouter API key for AI chat completions"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for image generation and chat"
    required: true
  ANTHROPIC_API_KEY:
    description: "Anthropic API key for Claude chat (optional)"
    required: false
  DISCORD_WEBHOOK_URL:
    description: "Discord webhook URL for notifications (optional)"
    required: false
  BLUESKY_APP_PASSWORD:
    description: "Bluesky app password for social posting (optional)"
    required: false

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Run hosting CI checks
      shell: bash
      run: |
        echo "🏗️ Running comprehensive hosting CI pipeline..."
        pnpm hosting:check

    - name: Create queue if needed
      shell: bash
      run: |
        cd hosting/pkg
        echo "📋 Ensuring queue exists..."

        # Create the queue if it doesn't exist (ignore error if it already exists)
        npx wrangler queues create publish-events-v2 || echo "ℹ️ Queue may already exist"

        echo "✅ Queue setup complete"
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}

    - name: Deploy to Cloudflare Workers
      shell: bash
      run: |
        cd hosting/pkg
        echo "🚀 Deploying vibes-hosting-v2 worker..."

        # Deploy the worker with simplified command
        npx wrangler deploy

        echo "✅ Worker deployed successfully"

        # Set output for worker URL
        echo "worker_url=https://vibes-hosting-v2.workers.dev" >> $GITHUB_OUTPUT
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}

    - name: Configure worker secrets
      shell: bash
      run: |
        cd hosting/pkg

        echo "🔐 Setting required API secrets..."

        # Required AI API keys
        echo "${{ inputs.SERVER_OPENROUTER_API_KEY }}" | npx wrangler secret put SERVER_OPENROUTER_API_KEY
        echo "${{ inputs.OPENAI_API_KEY }}" | npx wrangler secret put OPENAI_API_KEY

        echo "✅ Required secrets configured"

        # Optional Anthropic key
        if [ -n "${{ inputs.ANTHROPIC_API_KEY }}" ]; then
          echo "🔐 Setting Anthropic API key..."
          echo "${{ inputs.ANTHROPIC_API_KEY }}" | npx wrangler secret put ANTHROPIC_API_KEY
        else
          echo "ℹ️  Anthropic API key not provided (optional - Claude endpoints will be disabled)"
        fi

        # Optional secrets
        if [ -n "${{ inputs.DISCORD_WEBHOOK_URL }}" ]; then
          echo "🔐 Setting Discord webhook..."
          echo "${{ inputs.DISCORD_WEBHOOK_URL }}" | npx wrangler secret put DISCORD_WEBHOOK_URL
        else
          echo "ℹ️  Discord webhook not provided (optional)"
        fi

        if [ -n "${{ inputs.BLUESKY_APP_PASSWORD }}" ]; then
          echo "🔐 Setting Bluesky credentials..."
          echo "${{ inputs.BLUESKY_APP_PASSWORD }}" | npx wrangler secret put BLUESKY_APP_PASSWORD
        else
          echo "ℹ️  Bluesky password not provided (optional)"
        fi

        echo "✅ All secrets configured successfully"
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}

    - name: Upload KV assets
      shell: bash
      run: |
        cd hosting/pkg

        echo "📦 Uploading static assets to KV store..."

        # Upload favicon and babel assets
        pnpm kv:put-svg:remote || echo "⚠️  SVG upload failed, continuing..."
        pnpm kv:put-ico:remote || echo "⚠️  ICO upload failed, continuing..."
        pnpm kv:put-babel:remote || echo "⚠️  Babel upload failed, continuing..."

        echo "✅ Asset upload completed"
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}

    - name: Deployment summary
      shell: bash
      run: |
        echo ""
        echo "🎉 Deployment Summary"
        echo "===================="
        echo "✅ Worker: vibes-hosting-v2"
        echo "🌐 Worker URL: https://vibes-hosting-v2.workers.dev"
        echo ""
        echo "🔄 Production Deployment - Next Steps:"
        echo "1. Test the worker URL above"
        echo "2. Update domain routes in Cloudflare Dashboard:"
        echo "   - vibesdiy.work (test first)"
        echo "   - vibecode.garden"
        echo "   - vibes-diy-api.com" 
        echo "   - vibesdiy.app (production last)"
        echo "3. Monitor error rates and performance"
        echo "4. Keep old worker as backup for 30 days"
