name = "vibesbox"
main = "src/index.ts"
compatibility_date = "2024-10-01"

routes = [
  { pattern = "vibesbox.dev/*", zone_name = "vibesbox.dev" },
  { pattern = "*.vibesbox.dev/*", zone_name = "vibesbox.dev" }
]

[env.staging]
name = "vibesbox-staging"