name: Deploy Hosting Worker

on:
  # Production deployment on main only
  push:
    paths:
      - "hosting/**/*"
    branches:
      - main

  # Manual trigger for controlled deployments
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - production
          - dev
          - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'production' || github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup runtime environment
        uses: ./actions/runtime

      - name: Determine deployment type
        id: deployment
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "type=production" >> $GITHUB_OUTPUT  
            echo "worker_name=vibes-hosting-v2" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "type=manual" >> $GITHUB_OUTPUT
            echo "worker_name=vibes-hosting-v2" >> $GITHUB_OUTPUT
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy hosting worker
        id: deploy
        uses: ./hosting/actions/deploy
        with:
          environment: ${{ steps.deployment.outputs.environment }}
          worker_name: ${{ steps.deployment.outputs.worker_name }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          SERVER_OPENROUTER_API_KEY: ${{ secrets.SERVER_OPENROUTER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
