name: "use-vibes-publish"
on:
  push:
    paths:
      - "use-vibes/**/*"
    tags:
      - "use-vibes@*"

jobs:
  compile_test:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/core@s') && 'staging' || startsWith(github.ref, 'refs/tags/core@p') && 'production' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/runtime

      - name: install
        shell: bash
        run: pnpm install

      - name: format-check
        shell: bash
        run: pnpm run format --check

      - name: lint
        shell: bash
        run: |
          echo "We NEED to work on the linting"
          pnpm run lint || true

      - name: validate-all-packages
        shell: bash
        run: |
          set -e
          echo "Running root validation before publishing (SKIPPING TESTS)..."
          pnpm build
          echo "✅ All packages validated successfully (tests skipped)"

      - uses: ./use-vibes/actions/publish
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
